# This is the default configuration file for websites-update-detector
# @see https://github.com/Chuanwise/websites-update-detector

#websites:
#  xidian:
#    # name is only used in email
#    name: website-name
#    # url is used to query and send email
#    url: <url>
#    detector:
#      type: regexp
#      exp: target="_blank">(?<title>.+?)</a><span>
#      group: title
#    period: 60000
#    emails:
#      - <your email>

# smtp servers for sending notification
#smtp:
#  host: smtp.qq.com
#  port: 465
#  email: your-qq@qq.com
#  # auth is nullable
#  auth: your-qq-email-smtp-code
#  debug: true

# max fail count to cancel task
#maxFailCount: 1

# email to receive logs
#email:
#  - your-email@domain

# random query period scale
#randomMillisecondsScale: 180000